[theme]
base="light"
primaryColor="#7B68AE"
backgroundColor="#FAFAFE"
secondaryBackgroundColor="#EDEBF4"
textColor="#2D2A3E"
font="sans serif"


[browser]
gatherUsageStats = false

[server]
showEmailPrompt = false
port = 1337
